### ISSUE TITLE
OpenPGP Best Practices is not valid HTML, looks broken in Wayback Machine

### ISSUE THREAD

**Issue by nurupo** [riseupnet/riseup_help#563]
Scroll down to the bottom of the page and see a giant code block:
https://web.archive.org/web/20180626052023/https://riseup.net/en/security/message-security/openpgp/best-practices

[Looks like](https://validator.w3.org/nu/?doc=https%3A%2F%2Friseup.net%2Fen%2Fsecurity%2Fmessage-security%2Fopenpgp%2Fbest-practices) the issue might be caused by some HTML entities not being closed with `;`, specifically `&#064` in `john&#046;doe&#064example&#046;com`.

The source file for the article doesn't use HTML entities there, so it must be whatever converts the source material into the HTML that doesn't close the `@` entity with `;`.

**Comment by micah** [comment]
Thanks for the report, it seems like it is something specific with the
converter, and archive.org... as this issue does not show up on the original
page.

**Comment by nurupo** [comment]
The issue does show up in the original page. I even pointed it out it in my first comment.

If you look at the source of the page, you can see that it uses

```
<a href="mailto:john&#046;doe&#064example&#046;com">john&#046;doe&#064example&#046;com</a>
```

for the email, which has an error in it, `&#064` should have been `&#064;`, it's missing `;` at the end.
Even W3 Validator I have linked to points out the missing `;`. Your page is not a valid HTML, that missing `;` breaks HTML rules.

You don't see the page rendered weirdly in Chromium or Firefox because they are smart enough to be able to correct the missing `;`, however, not all browser engines are that smart and they will render the page incorrectly, just like the the Wayback Machine did.

The issue is that the Risenup page is invalid HTML, please fix it.

**Comment by kradan** [comment]
This has been fixed in master.

**Comment by nurupo** [comment]
Not fixed, please reopen.

**Comment by nurupo** [comment]
The way the website is live right now:
- `&#064` still doesn't end with a `;`, making it invalid HTML
- W3 HTML Checker [still complains about it](https://validator.w3.org/nu/?doc=https%3A%2F%2Friseup.net%2Fen%2Fsecurity%2Fmessage-security%2Fopenpgp%2Fbest-practices), marking it as an Error:

    >Error: Character reference was not terminated by a semicolon.
    >At line 381, column 62
    >`n&#046;doe&#064example&#046;co`

- WayBack Machine [doesn't tolerate the invalid HTML error and breaks how the archived page is rendered](https://web.archive.org/web/20200730211451/https://riseup.net/en/security/message-security/openpgp/best-practices):

![WayBack Machine](https://user-images.githubusercontent.com/1855294/90693657-36e7c080-e245-11ea-941d-ec716b9a0739.png)

So it's the same as it was at the time of filing the issue.

**Comment by disturbio** [comment]
@nurupo is correct, but this is not a bug in our documentation but in the software that creates the static output, ambar. This is not a problem from archive.org, which we can't ask them to be as forgiving as web browsers.

But I'm not going to re-open this issue for two reasons. 

1) We are trying to move away from ambar
2) We are deprecating that document for now since it needs to be rebuilt as GnuPG has by default better configuration options and there are problematic information in there that can lead to never refresh your public key ring...

**Comment by nurupo** [comment]
Fair enough.
